# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "accounts", :force => true do |t|
    t.column "owner_id",         :integer
    t.column "short_name",       :string,                      :null => false
    t.column "blocked",          :boolean,  :default => false, :null => false
    t.column "name",             :string,                      :null => false
    t.column "name_for_sorting", :string
    t.column "logo",             :string
    t.column "direct_login",     :boolean,  :default => false
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "chpass_tokens", :force => true do |t|
    t.column "account_id", :integer,  :null => false
    t.column "token",      :string,   :null => false
    t.column "created_at", :datetime
  end

  add_index "chpass_tokens", ["account_id"], :name => "account_id"
  add_index "chpass_tokens", ["token"], :name => "index_chpass_tokens_on_token"

  create_table "expense_types", :force => true do |t|
    t.column "account_id",       :integer,  :null => false
    t.column "url_id",           :string,   :null => false
    t.column "name",             :string,   :null => false
    t.column "name_for_sorting", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  add_index "expense_types", ["account_id"], :name => "account_id"
  add_index "expense_types", ["url_id"], :name => "index_expense_types_on_url_id"

  create_table "expenses", :force => true do |t|
    t.column "account_id",           :integer,                                 :null => false
    t.column "project_id",           :integer,                                 :null => false
    t.column "expense_type_id",      :integer,                                 :null => false
    t.column "date",                 :date
    t.column "amount",               :decimal,  :precision => 10, :scale => 2
    t.column "concept",              :string,                                  :null => false
    t.column "concept_for_sorting",  :string
    t.column "notes",                :text
    t.column "envelope",             :string
    t.column "envelope_for_sorting", :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
  end

  add_index "expenses", ["account_id"], :name => "account_id"
  add_index "expenses", ["project_id"], :name => "project_id"
  add_index "expenses", ["expense_type_id"], :name => "expense_type_id"

  create_table "login_tokens", :force => true do |t|
    t.column "account_id", :integer
    t.column "project_id", :integer
    t.column "type",       :string
    t.column "token",      :string,   :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "login_tokens", ["account_id"], :name => "account_id"
  add_index "login_tokens", ["project_id"], :name => "project_id"
  add_index "login_tokens", ["token"], :name => "index_login_tokens_on_token"

  create_table "open_id_authentication_associations", :force => true do |t|
    t.column "server_url", :binary
    t.column "handle",     :string
    t.column "secret",     :binary
    t.column "issued",     :integer
    t.column "lifetime",   :integer
    t.column "assoc_type", :string
  end

  create_table "open_id_authentication_nonces", :force => true do |t|
    t.column "timestamp",  :integer, :null => false
    t.column "server_url", :string
    t.column "salt",       :string,  :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "account_id",              :integer,  :null => false
    t.column "url_id",                  :string,   :null => false
    t.column "name",                    :string
    t.column "name_for_sorting",        :string
    t.column "description",             :string
    t.column "description_for_sorting", :string
    t.column "notes",                   :text
    t.column "created_at",              :datetime
    t.column "updated_at",              :datetime
  end

  add_index "projects", ["account_id"], :name => "account_id"
  add_index "projects", ["url_id"], :name => "index_projects_on_url_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "account_id",                :integer,                                   :null => false
    t.column "first_name",                :string
    t.column "first_name_for_sorting",    :string
    t.column "last_name",                 :string
    t.column "last_name_for_sorting",     :string
    t.column "last_seen_at",              :datetime
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "is_blocked",                :boolean,                :default => false
    t.column "openid_url",                :string
  end

  add_index "users", ["account_id"], :name => "account_id"

end
